/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OrganicFarmingRouteImport } from './routes/organic-farming'
import { Route as MarketPricesRouteImport } from './routes/market-prices'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DiseaseDiagnosisRouteImport } from './routes/disease-diagnosis'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CropRecommendationRouteImport } from './routes/crop-recommendation'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as IndexRouteImport } from './routes/index'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganicFarmingRoute = OrganicFarmingRouteImport.update({
  id: '/organic-farming',
  path: '/organic-farming',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketPricesRoute = MarketPricesRouteImport.update({
  id: '/market-prices',
  path: '/market-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseDiagnosisRoute = DiseaseDiagnosisRouteImport.update({
  id: '/disease-diagnosis',
  path: '/disease-diagnosis',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CropRecommendationRoute = CropRecommendationRouteImport.update({
  id: '/crop-recommendation',
  path: '/crop-recommendation',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/crop-recommendation': typeof CropRecommendationRoute
  '/dashboard': typeof DashboardRoute
  '/disease-diagnosis': typeof DiseaseDiagnosisRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/market-prices': typeof MarketPricesRoute
  '/organic-farming': typeof OrganicFarmingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/crop-recommendation': typeof CropRecommendationRoute
  '/dashboard': typeof DashboardRoute
  '/disease-diagnosis': typeof DiseaseDiagnosisRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/market-prices': typeof MarketPricesRoute
  '/organic-farming': typeof OrganicFarmingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/crop-recommendation': typeof CropRecommendationRoute
  '/dashboard': typeof DashboardRoute
  '/disease-diagnosis': typeof DiseaseDiagnosisRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/market-prices': typeof MarketPricesRoute
  '/organic-farming': typeof OrganicFarmingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/weather': typeof WeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-chat'
    | '/crop-recommendation'
    | '/dashboard'
    | '/disease-diagnosis'
    | '/feedback'
    | '/login'
    | '/market-prices'
    | '/organic-farming'
    | '/reset-password'
    | '/signup'
    | '/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-chat'
    | '/crop-recommendation'
    | '/dashboard'
    | '/disease-diagnosis'
    | '/feedback'
    | '/login'
    | '/market-prices'
    | '/organic-farming'
    | '/reset-password'
    | '/signup'
    | '/weather'
  id:
    | '__root__'
    | '/'
    | '/ai-chat'
    | '/crop-recommendation'
    | '/dashboard'
    | '/disease-diagnosis'
    | '/feedback'
    | '/login'
    | '/market-prices'
    | '/organic-farming'
    | '/reset-password'
    | '/signup'
    | '/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiChatRoute: typeof AiChatRoute
  CropRecommendationRoute: typeof CropRecommendationRoute
  DashboardRoute: typeof DashboardRoute
  DiseaseDiagnosisRoute: typeof DiseaseDiagnosisRoute
  FeedbackRoute: typeof FeedbackRoute
  LoginRoute: typeof LoginRoute
  MarketPricesRoute: typeof MarketPricesRoute
  OrganicFarmingRoute: typeof OrganicFarmingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  WeatherRoute: typeof WeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organic-farming': {
      id: '/organic-farming'
      path: '/organic-farming'
      fullPath: '/organic-farming'
      preLoaderRoute: typeof OrganicFarmingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-prices': {
      id: '/market-prices'
      path: '/market-prices'
      fullPath: '/market-prices'
      preLoaderRoute: typeof MarketPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease-diagnosis': {
      id: '/disease-diagnosis'
      path: '/disease-diagnosis'
      fullPath: '/disease-diagnosis'
      preLoaderRoute: typeof DiseaseDiagnosisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-recommendation': {
      id: '/crop-recommendation'
      path: '/crop-recommendation'
      fullPath: '/crop-recommendation'
      preLoaderRoute: typeof CropRecommendationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiChatRoute: AiChatRoute,
  CropRecommendationRoute: CropRecommendationRoute,
  DashboardRoute: DashboardRoute,
  DiseaseDiagnosisRoute: DiseaseDiagnosisRoute,
  FeedbackRoute: FeedbackRoute,
  LoginRoute: LoginRoute,
  MarketPricesRoute: MarketPricesRoute,
  OrganicFarmingRoute: OrganicFarmingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  WeatherRoute: WeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
